import { auth } from "@/auth"
import { redirect } from "next/navigation"
import Link from "next/link"
import { formatCurrency } from "@/lib/utils"
import { prisma } from "@/lib/prisma"
import { resolveFYFromSearchParams, buildPaymentDateFilter } from "@/lib/financialYear"
import { FinancialYearSelector } from "@/components/financial-year/FinancialYearSelector"
import { Suspense } from "react"

interface Campaign {
  id: string
  name: string
  normalizedName: string
  autoGenerated: boolean
  department: {
    id: string
    name: string
  }
  paymentCount: number
  totalAmount: number
  createdAt: string
  updatedAt: string
}

async function getCampaigns(startDate?: Date, endDate?: Date): Promise<Campaign[]> {
  const dateFilter = startDate && endDate
    ? buildPaymentDateFilter(startDate, endDate)
    : {}

  const campaigns = await prisma.campaignCategory.findMany({
    include: {
      department: {
        select: {
          id: true,
          name: true,
        },
      },
      _count: {
        select: {
          payments: { where: dateFilter },
        },
      },
      payments: {
        select: {
          amount: true,
        },
        where: dateFilter,
      },
    },
    orderBy: [
      { autoGenerated: "asc" },
      { name: "asc" },
    ],
  })

  return campaigns.map((campaign) => {
    const totalAmount = campaign.payments.reduce((sum, payment) => {
      return sum + Number(payment.amount)
    }, 0)

    return {
      id: campaign.id,
      name: campaign.name,
      normalizedName: campaign.normalizedName,
      autoGenerated: campaign.autoGenerated,
      department: campaign.department,
      paymentCount: campaign._count.payments,
      totalAmount,
      createdAt: campaign.createdAt.toISOString(),
      updatedAt: campaign.updatedAt.toISOString(),
    }
  })
}

export default async function CampaignsPage({
  searchParams,
}: {
  searchParams: Promise<{ [key: string]: string | string[] | undefined }>
}) {
  const session = await auth()

  if (!session?.user) {
    redirect("/login")
  }

  const resolvedSearchParams = await searchParams
  const fyParam = resolvedSearchParams.fy as string | undefined
  const { startDate: fyStartDate, endDate: fyEndDate, label: fyLabel } = 
    await resolveFYFromSearchParams(fyParam, prisma)

  const campaigns = await getCampaigns(fyStartDate, fyEndDate)
  const isAdmin = session.user.role === "SUPER_ADMIN" || session.user.role === "ZONE_ADMIN"

  const manualCampaigns = campaigns.filter((c) => !c.autoGenerated)
  const autoCampaigns = campaigns.filter((c) => c.autoGenerated)

  const totalAmount = campaigns.reduce((sum, c) => sum + c.totalAmount, 0)
  const totalPayments = campaigns.reduce((sum, c) => sum + c.paymentCount, 0)

  return (
    <div className="space-y-8">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-3xl font-bold tracking-tight text-slate-900">
            Campaigns
          </h1>
          <p className="mt-2 text-slate-600">
            Track fundraising campaigns across zones, groups, and churches.{" "}
            Viewing <span className="font-semibold">{fyLabel}</span>.
          </p>
        </div>
        <div className="flex items-center gap-3">
          <Suspense fallback={<div className="h-10 w-32 animate-pulse rounded-md bg-slate-100" />}>
            <FinancialYearSelector />
          </Suspense>
          {isAdmin && (
            <Link
              href="/dashboard/campaigns/new"
              className="rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white shadow-md transition hover:bg-blue-700"
            >
              Create Campaign
            </Link>
          )}
        </div>
      </div>

      <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
        <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm font-medium text-slate-600">Total Campaigns</p>
              <p className="mt-2 text-3xl font-bold text-slate-900">
                {campaigns.length}
              </p>
            </div>
            <div className="rounded-xl bg-blue-50 p-3">
              <svg
                className="h-6 w-6 text-blue-600"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"
                />
              </svg>
            </div>
          </div>
        </div>

        <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm font-medium text-slate-600">Manual Campaigns</p>
              <p className="mt-2 text-3xl font-bold text-slate-900">
                {manualCampaigns.length}
              </p>
            </div>
            <div className="rounded-xl bg-green-50 p-3">
              <svg
                className="h-6 w-6 text-green-600"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M12 4v16m8-8H4"
                />
              </svg>
            </div>
          </div>
        </div>

        <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm font-medium text-slate-600">Total Raised</p>
              <p className="mt-2 text-3xl font-bold text-slate-900">
                {formatCurrency(totalAmount)}
              </p>
            </div>
            <div className="rounded-xl bg-emerald-50 p-3">
              <svg
                className="h-6 w-6 text-emerald-600"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                />
              </svg>
            </div>
          </div>
        </div>

        <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-sm font-medium text-slate-600">Total Payments</p>
              <p className="mt-2 text-3xl font-bold text-slate-900">
                {totalPayments}
              </p>
            </div>
            <div className="rounded-xl bg-purple-50 p-3">
              <svg
                className="h-6 w-6 text-purple-600"
                fill="none"
                stroke="currentColor"
                viewBox="0 0 24 24"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2"
                />
              </svg>
            </div>
          </div>
        </div>
      </div>

      {manualCampaigns.length > 0 && (
        <div className="space-y-4">
          <h2 className="text-xl font-semibold text-slate-900">
            Manual Campaigns ({manualCampaigns.length})
          </h2>
          <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
            <table className="min-w-full divide-y divide-slate-200">
              <thead className="bg-slate-50">
                <tr>
                  <th className="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wider text-slate-600">
                    Campaign Name
                  </th>
                  <th className="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wider text-slate-600">
                    Department
                  </th>
                  <th className="px-6 py-4 text-right text-xs font-semibold uppercase tracking-wider text-slate-600">
                    Total Raised
                  </th>
                  <th className="px-6 py-4 text-right text-xs font-semibold uppercase tracking-wider text-slate-600">
                    Payments
                  </th>
                  <th className="px-6 py-4 text-right text-xs font-semibold uppercase tracking-wider text-slate-600">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200 bg-white">
                {manualCampaigns.map((campaign) => (
                  <tr key={campaign.id} className="hover:bg-slate-50">
                    <td className="px-6 py-4">
                      <Link
                        href={`/dashboard/campaigns/${campaign.id}`}
                        className="font-medium text-blue-600 hover:text-blue-800"
                      >
                        {campaign.name}
                      </Link>
                    </td>
                    <td className="px-6 py-4 text-sm text-slate-600">
                      {campaign.department.name}
                    </td>
                    <td className="px-6 py-4 text-right font-semibold text-slate-900">
                      {formatCurrency(campaign.totalAmount)}
                    </td>
                    <td className="px-6 py-4 text-right text-sm text-slate-600">
                      {campaign.paymentCount}
                    </td>
                    <td className="px-6 py-4 text-right">
                      <Link
                        href={`/dashboard/campaigns/${campaign.id}`}
                        className="text-sm text-blue-600 hover:text-blue-800"
                      >
                        View Details →
                      </Link>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {autoCampaigns.length > 0 && (
        <div className="space-y-4">
          <h2 className="text-xl font-semibold text-slate-900">
            Auto-Generated Campaigns ({autoCampaigns.length})
          </h2>
          <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
            <table className="min-w-full divide-y divide-slate-200">
              <thead className="bg-slate-50">
                <tr>
                  <th className="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wider text-slate-600">
                    Campaign Name
                  </th>
                  <th className="px-6 py-4 text-left text-xs font-semibold uppercase tracking-wider text-slate-600">
                    Department
                  </th>
                  <th className="px-6 py-4 text-right text-xs font-semibold uppercase tracking-wider text-slate-600">
                    Total Raised
                  </th>
                  <th className="px-6 py-4 text-right text-xs font-semibold uppercase tracking-wider text-slate-600">
                    Payments
                  </th>
                  <th className="px-6 py-4 text-right text-xs font-semibold uppercase tracking-wider text-slate-600">
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200 bg-white">
                {autoCampaigns.map((campaign) => (
                  <tr key={campaign.id} className="hover:bg-slate-50">
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-2">
                        <Link
                          href={`/dashboard/campaigns/${campaign.id}`}
                          className="font-medium text-blue-600 hover:text-blue-800"
                        >
                          {campaign.name}
                        </Link>
                        <span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs text-slate-600">
                          Auto
                        </span>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-sm text-slate-600">
                      {campaign.department.name}
                    </td>
                    <td className="px-6 py-4 text-right font-semibold text-slate-900">
                      {formatCurrency(campaign.totalAmount)}
                    </td>
                    <td className="px-6 py-4 text-right text-sm text-slate-600">
                      {campaign.paymentCount}
                    </td>
                    <td className="px-6 py-4 text-right">
                      <Link
                        href={`/dashboard/campaigns/${campaign.id}`}
                        className="text-sm text-blue-600 hover:text-blue-800"
                      >
                        View Details →
                      </Link>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}

      {campaigns.length === 0 && (
        <div className="rounded-2xl border border-slate-200 bg-white p-12 text-center shadow-sm">
          <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-full bg-slate-100">
            <svg
              className="h-8 w-8 text-slate-400"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"
              />
            </svg>
          </div>
          <h3 className="mt-4 text-lg font-semibold text-slate-900">
            No campaigns yet
          </h3>
          <p className="mt-2 text-slate-600">
            Create your first campaign or upload transaction data to auto-generate campaigns.
          </p>
          {isAdmin && (
            <Link
              href="/dashboard/campaigns/new"
              className="mt-6 inline-flex items-center rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white shadow-md transition hover:bg-blue-700"
            >
              Create Campaign
            </Link>
          )}
        </div>
      )}
    </div>
  )
}
