-- Create enum for upload types
CREATE TYPE "UploadType" AS ENUM ('ORDER', 'TRANSACTION');

-- Create table for campaign categories
CREATE TABLE "CampaignCategory" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "normalizedName" TEXT NOT NULL,
    "autoGenerated" BOOLEAN NOT NULL DEFAULT TRUE,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "departmentId" TEXT NOT NULL,
    CONSTRAINT "CampaignCategory_pkey" PRIMARY KEY ("id")
);

-- Extend upload history with type tracking
ALTER TABLE "UploadHistory"
    ADD COLUMN "uploadType" "UploadType" NOT NULL DEFAULT 'TRANSACTION';

-- Extend payments with campaign metadata
ALTER TABLE "Payment"
    ADD COLUMN "campaignLabel" TEXT,
    ADD COLUMN "campaignCategoryId" TEXT;

-- Indexes and constraints for campaign categories
CREATE UNIQUE INDEX "CampaignCategory_departmentId_normalizedName_key"
    ON "CampaignCategory" ("departmentId", "normalizedName");

CREATE INDEX "CampaignCategory_departmentId_idx"
    ON "CampaignCategory" ("departmentId");

CREATE INDEX "Payment_campaignCategoryId_idx"
    ON "Payment" ("campaignCategoryId");

-- Foreign key relationships
ALTER TABLE "CampaignCategory"
    ADD CONSTRAINT "CampaignCategory_departmentId_fkey" FOREIGN KEY ("departmentId")
    REFERENCES "Department" ("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Payment"
    ADD CONSTRAINT "Payment_campaignCategoryId_fkey" FOREIGN KEY ("campaignCategoryId")
    REFERENCES "CampaignCategory" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
